name: Data passing workflow
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Data
      run: echo "some data generated in job1" > data.txt
    - name: Upload data as artifact
      uses: actions/upload-artifact@v4
      with:
        name: data-artifact
        path: data.txt
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Download the data artifact
      uses: actions/download-arctifact@v4
      with:
        name: data-artifact
        path: data/
    - name: Use data in job2
      run: cat data/data.txt
