name: Publish to github package
on: [push]

jobs:
  build_and_push:
  runs-on: ubuntu-latest
  steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install
    - name: Build Package
      run: npm run build
    - name: Package the app
      run: npm pack
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: '*.tgz'
  package:
