name: Publish to github package
on: [push]

jobs:
  build_and_package:
   runs-on: ubuntu-latest
   steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install
    - name: Build Package
      run: npm run build
    - name: Package the app
      run: npm pack
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: '*.tgz'
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: [build_and_package]
    steps:
      - name: Download packages
        uses: actions/download-artifact@v2
        with:
          name: package
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@Yashaswini18'
      - run: echo "registry=https://npm.pkg.github.com/@Yashaswini18" >> .npmc
      - run: npm publish $(ls *.tgz)
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
          
